### PR TITLE
docs(react): simplify usage instructions and demo introduced in @esri/calcite-components@1.5.0

### PR DESCRIPTION
**Pull request by jcfranco**
1.5.0 simplifies component imports in React and this updates the example/doc accordingly.

This also includes some minor doc tweaks.

### CODE REVIEW

**Comment by jcfranco** [comment]
Once 1.5.0 is officially released, this should be updated to reference the latest package version and marked ready for review.

**Review by geospatialem — APPROVED** [review]
💥💣💥  Awesome - thanks for putting together to showcase this awesome feature! 💥💣💥  

From our conversation earlier, let's hold off on merging until `1.5.0` is live. 🎸

**Comment by geospatialem** [comment]
> Once 1.5.0 is officially released, this should be updated to reference the latest package version and marked ready for review.

Updated to 1.5.0, @jcfranco want to take a quick peek to make sure all looks in order? 👁️ 👃🏻 👁️

**Comment by jcfranco** [comment]
@geospatialem Looks great!

**Pull request merged**
